### ISSUE TITLE
Link to the documentation is dead

### ISSUE THREAD

**Issue by vhama** [Kitware/MetaIO#133]
Hi,
The link to the documentation in the readme seems to be dead: http://www.itk.org/Wiki/ITK/MetaIO/Documentation 

"Forbidden
You don't have permission to access this resource."

**Comment by dzenanz** [comment]
Fixed now. Also reported here: https://discourse.itk.org/t/metaio-documentation/7497/5

**Comment by vhama** [comment]
Thanks for the quick reply! I still have the same issue and get the 403 Forbidden when trying to access the page... Maybe it needs some time to be updated ?

**Comment by thewtex** [comment]
The documentation has been ported to markdown / ITK's ReadTheDocs documentation: https://github.com/InsightSoftwareConsortium/ITK/pull/5311

**Comment by thewtex** [comment]
Addressed in: https://github.com/Kitware/MetaIO/pull/134
